roboflow_api_key: ''  # Robofow API key
video_path: '' # Path to video file
CLIP:
  - "bed"
  - "chair"
  - "couch"
  - "wall"
  - "rug"
  - "table"
  - "door"
  - "stairs"
  - "television"
  - "kitchen"